### ISSUE TITLE
https://github.com/suse-edge/fleet-examples/blob/main/fleets/simple broken

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/fleet-examples#13]
The "Simple" example link in the readme is broken. Seems to have been refactored, but the readme page hasn't been updated yet?

**Comment by jtomasek** [comment]
Looks like all of the 'fleets' links from README are broken since the original 'fleets' examples have been moved to `fleets/general`

**Comment by joesusecom** [comment]
There's a new subfolder structure with "general" and "day2". This also seems to affect other links.

**Comment by ipetrov117** [comment]
I'll open a PR fixing this later today.
